name: Actions Runner Controller Demo
on:
  workflow_dispatch:
      inputs:
        delay:
          description: 'Delay in seconds before starting the runner'
          required: true
          default: '2'

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"